# Updated by GitHub contribution automation.
"""Additional Patel family memories for a rich flagship archive (~50 total)."""

EXTENDED_FLAGSHIP_MEMORIES = [
    {
        "id": "fam_16",
        "title": "Grandmother's Kitchen in Dadar",
        "summary": "Grandmother taught mother her dal recipe during a monsoon afternoon in Dadar.",
        "raw_text": "Grandmother stood in the small Dadar kitchen while rain hit the shutters. She taught mother the family dal recipe and told stories about feeding dock workers when grandfather first worked at the port.",
        "structured_data": {
            "people": ["Grandmother", "Mother", "Grandfather"],
            "places": ["Dadar", "Mumbai"],
            "events": ["Cooking", "Family recipes"],
            "dates": ["1990"],
            "summary": "Grandmother shared recipes and port-era stories in Dadar.",
        },
    },
    {
        "id": "fam_17",
        "title": "Diwali on the Terrace",
        "summary": "Family celebrated Diwali on grandfather's terrace with lamps and old songs.",
        "raw_text": "Every Diwali we lit lamps on grandfather's terrace in Mumbai. Father sang songs he learned as a boy, and grandfather told us how the neighborhood looked in the 1960s when the port expanded.",
        "structured_data": {
            "people": ["Grandfather", "Father", "Mother", "Me"],
            "places": ["Dadar Terrace", "Mumbai"],
            "events": ["Diwali", "Festival"],
            "dates": ["2010"],
            "summary": "Diwali celebrations connected generations on the terrace.",
        },
    },
    {
        "id": "fam_18",
        "title": "Rahul's Visit from Pune",
        "summary": "Father's college friend Rahul visited Bangalore and retold Pune hostel stories.",
        "raw_text": "Rahul visited our home in Bangalore. He and father laughed about engineering hostel nights in Pune in 1998, the broken fan, and grandfather calling every Sunday.",
        "structured_data": {
            "people": ["Father", "Rahul", "Grandfather"],
            "places": ["Bangalore", "Pune"],
            "events": ["Friend visit", "College memories"],
            "dates": ["2012"],
            "summary": "College friendship stories resurfaced during Rahul's visit.",
        },
    },
    {
        "id": "fam_19",
        "title": "Cousin Neha's Letter from Delhi",
        "summary": "Neha mailed a letter describing her Delhi bookstore and family connections.",
        "raw_text": "Cousin Neha wrote from Delhi about her bookstore near Connaught Place. She reminded us that mother's family met father's at her wedding in 2005 and attached a photo of grandfather blessing the couple.",
        "structured_data": {
            "people": ["Neha", "Mother", "Father", "Grandfather"],
            "places": ["Delhi"],
            "events": ["Letter", "Family connection"],
            "dates": ["2014"],
            "summary": "Neha's letter linked Delhi and Mumbai family lines.",
        },
    },
    {
        "id": "fam_20",
        "title": "Grandfather at the Port — Photo Scan",
        "summary": "Scanned photo of young grandfather at Mumbai port office circa 1962.",
        "raw_text": "We scanned a brittle photo of grandfather in front of the Mumbai port office in 1962. Father labeled it for the archive and said it should sit beside memories of Marine Drive walks.",
        "structured_data": {
            "people": ["Grandfather", "Father"],
            "places": ["Port Office", "Mumbai"],
            "events": ["Photo archive", "Scanning"],
            "dates": ["1962", "2018"],
            "summary": "Historic port photo preserved in the digital archive.",
        },
    },
    {
        "id": "fam_21",
        "title": "Mother's First Visit to Marine Drive",
        "summary": "Mother first walked Marine Drive with father while grandfather narrated port history.",
        "raw_text": "Mother told us her first Marine Drive walk with father was in 2006, before their wedding. Grandfather joined them and pointed to lights that mirrored the docks of his youth.",
        "structured_data": {
            "people": ["Mother", "Father", "Grandfather"],
            "places": ["Marine Drive", "Mumbai"],
            "events": ["First visit", "Courtship"],
            "dates": ["2006"],
            "summary": "Marine Drive walk during parents' courtship.",
        },
    },
    {
        "id": "fam_22",
        "title": "Father's Difficult Year — 2021",
        "summary": "Business struggled in 2021; grandfather's letter and family meetings kept spirits up.",
        "raw_text": "In 2021 father's business faced a difficult year. Grandfather's handwritten letter, mother's cooking, and Amit's weekly calls reminded us the archive exists so hard seasons are never forgotten.",
        "structured_data": {
            "people": ["Father", "Grandfather", "Mother", "Amit"],
            "places": ["Bangalore"],
            "events": ["Business challenge", "Family support"],
            "dates": ["2021"],
            "summary": "Family supported father through a difficult business year.",
        },
    },
    {
        "id": "fam_23",
        "title": "Cricket on Dadar Street",
        "summary": "Father and grandfather played street cricket with neighborhood children in the 1980s.",
        "raw_text": "Father described playing cricket on Dadar street with grandfather after school in the 1980s. Grandmother brought lime water and scolded them when the ball hit a vendor cart.",
        "structured_data": {
            "people": ["Father", "Grandfather", "Grandmother"],
            "places": ["Dadar", "Mumbai"],
            "events": ["Cricket", "Childhood"],
            "dates": ["1985"],
            "summary": "Street cricket memories in Dadar.",
        },
    },
    {
        "id": "fam_24",
        "title": "Amit and Father — First Office Photo",
        "summary": "Photo of father and Amit at their first Bangalore office in 2008.",
        "raw_text": "A framed photo shows father and Amit at their first Bangalore office in 2008. Grandfather visited the same week and said the cramped desk reminded him of the port clerk room.",
        "structured_data": {
            "people": ["Father", "Amit", "Grandfather"],
            "places": ["Bangalore", "First Office"],
            "events": ["Business launch", "Photo"],
            "dates": ["2008"],
            "summary": "First office moment for father and Amit's venture.",
        },
    },
    {
        "id": "fam_25",
        "title": "Monsoon Wedding Planning Calls",
        "summary": "Parents planned their wedding during monsoon season with grandfather coordinating Mumbai family.",
        "raw_text": "Mother saved phone logs from 2005 monsoon wedding planning. Grandfather coordinated Mumbai relatives while Neha's family handled Delhi ceremonies. Father commuted between cities.",
        "structured_data": {
            "people": ["Mother", "Father", "Grandfather", "Neha"],
            "places": ["Delhi", "Mumbai"],
            "events": ["Wedding planning"],
            "dates": ["2005"],
            "summary": "Cross-city wedding planning in monsoon season.",
        },
    },
    {
        "id": "fam_26",
        "title": "Great-Grandfather at the Docks — Oral History",
        "summary": "Grandfather recorded stories about great-grandfather working Mumbai docks.",
        "raw_text": "Grandfather recorded an oral history about great-grandfather loading ships at Mumbai docks before the family moved to Dadar. Father transcribed it for the archive.",
        "structured_data": {
            "people": ["Grandfather", "Great-grandfather", "Father"],
            "places": ["Mumbai Docks", "Dadar"],
            "events": ["Oral history"],
            "dates": ["2017"],
            "summary": "Dock-worker stories preserved as oral history.",
        },
    },
    {
        "id": "fam_27",
        "title": "Sarah — Wedding Photographer's Notes",
        "summary": "Wedding photographer Sarah left notes naming every family member in Delhi photos.",
        "raw_text": "Sarah, our wedding photographer, sent annotated contact sheets from Delhi. Grandfather corrected two names and added stories for each cousin in the margins.",
        "structured_data": {
            "people": ["Sarah", "Grandfather", "Mother", "Father"],
            "places": ["Delhi", "Mountain Resort"],
            "events": ["Wedding", "Photography"],
            "dates": ["2006"],
            "summary": "Photographer's notes enriched wedding archive metadata.",
        },
    },
    {
        "id": "fam_28",
        "title": "Pune Hostel — Late Night Projects",
        "summary": "Father and Rahul built electronics projects in Pune hostel; called grandfather weekly.",
        "raw_text": "Father's Pune hostel journal mentions late nights with Rahul building radios. He called grandfather every Sunday from the hostel phone booth about grades and Marine Drive dreams.",
        "structured_data": {
            "people": ["Father", "Rahul", "Grandfather"],
            "places": ["Pune", "Engineering College Hostel"],
            "events": ["College projects"],
            "dates": ["1999"],
            "summary": "Engineering hostel creativity and weekly grandfather calls.",
        },
    },
    {
        "id": "fam_29",
        "title": "Grandmother's Prayer Room Shelf",
        "summary": "Cataloged items on grandmother's prayer shelf — photos, letters, wedding garland.",
        "raw_text": "We photographed grandmother's prayer room shelf in Dadar: wedding garland, grandfather's port ID copy, and letters from mother's Delhi family.",
        "structured_data": {
            "people": ["Grandmother", "Grandfather", "Mother"],
            "places": ["Dadar", "Mumbai"],
            "events": ["Archive catalog"],
            "dates": ["2022"],
            "summary": "Sacred family objects documented for the archive.",
        },
    },
    {
        "id": "fam_30",
        "title": "Family Reunion Train Journey",
        "summary": "Whole family took the train to Mumbai for grandfather's birthday reunion.",
        "raw_text": "We took an overnight train to Mumbai for grandfather's reunion. Father organized berths, mother packed food, and we practiced stories to record when we arrived in Dadar.",
        "structured_data": {
            "people": ["Grandfather", "Father", "Mother", "Me", "Amit"],
            "places": ["Mumbai", "Dadar"],
            "events": ["Train journey", "Reunion"],
            "dates": ["2016"],
            "summary": "Train journey to Mumbai family reunion.",
        },
    },
    {
        "id": "fam_31",
        "title": "Mr. Mehta — Internship Mentor Note",
        "summary": "Mr. Mehta wrote a recommendation letter for father after 2000 Mumbai internship.",
        "raw_text": "Mr. Mehta's recommendation letter praised father's discipline from the 2000 internship. Grandfather kept a copy folded inside his Marine Drive walking journal.",
        "structured_data": {
            "people": ["Father", "Mr. Mehta", "Grandfather"],
            "places": ["Mumbai"],
            "events": ["Internship", "Recommendation"],
            "dates": ["2000"],
            "summary": "Mentor letter from father's first Mumbai internship.",
        },
    },
    {
        "id": "fam_32",
        "title": "Bangalore Garden — Mother's Herbs",
        "summary": "Mother planted herbs in Bangalore garden; grandfather approved by video call.",
        "raw_text": "Mother planted tulsi and curry leaves in our Bangalore garden. Grandfather watched on video call from Mumbai and told stories about grandmother's Dadar window plants.",
        "structured_data": {
            "people": ["Mother", "Grandfather", "Grandmother"],
            "places": ["Bangalore", "Dadar"],
            "events": ["Garden", "Video call"],
            "dates": ["2020"],
            "summary": "Gardening connected Bangalore home to Mumbai roots.",
        },
    },
    {
        "id": "fam_33",
        "title": "Archive Project Kickoff Dinner",
        "summary": "Father announced the family digital archive project at Sunday dinner.",
        "raw_text": "Father announced the MemoryGraph archive project at Sunday dinner. Grandfather placed his photo trunk on the table and said every grandchild should be able to ask questions with sources.",
        "structured_data": {
            "people": ["Father", "Grandfather", "Mother", "Me"],
            "places": ["Bangalore"],
            "events": ["Archive planning"],
            "dates": ["2023"],
            "summary": "Family archive project officially started at dinner.",
        },
    },
    {
        "id": "fam_34",
        "title": "Voice Note — Terrace Stories",
        "summary": "Voice note of grandfather singing an old monsoon song on the terrace.",
        "raw_text": "Audio file: grandfather singing a monsoon song on the Dadar terrace while father clapped. Wind noise and distant train horns in the background.",
        "structured_data": {
            "people": ["Grandfather", "Father"],
            "places": ["Dadar Terrace", "Mumbai"],
            "events": ["Voice recording", "Music"],
            "dates": ["2019"],
            "summary": "Grandfather's voice preserved from terrace evening.",
        },
    },
    {
        "id": "fam_35",
        "title": "Mountain Resort Wedding — Snow Photos",
        "summary": "Wedding photos from mountain resort; grandfather wore wool shawl from Mumbai.",
        "raw_text": "Mountain resort wedding photos show snow on pines and grandfather in a wool shawl mother brought from Mumbai. Neha stood beside mother holding marigold garlands.",
        "structured_data": {
            "people": ["Mother", "Father", "Grandfather", "Neha"],
            "places": ["Mountain Resort", "Delhi"],
            "events": ["Wedding"],
            "dates": ["2006"],
            "summary": "Mountain wedding photos in the archive.",
        },
    },
    {
        "id": "fam_36",
        "title": "Father Age 25 — Bangalore First Apartment",
        "summary": "Father's first Bangalore apartment in 2003; grandfather helped paint walls.",
        "raw_text": "When father was twenty-five he rented his first Bangalore apartment. Grandfather visited, helped paint walls blue, and left a Marine Drive postcard on the fridge.",
        "structured_data": {
            "people": ["Father", "Grandfather"],
            "places": ["Bangalore"],
            "events": ["First apartment"],
            "dates": ["2003"],
            "summary": "Father's early independence in Bangalore at age 25.",
        },
    },
    {
        "id": "fam_37",
        "title": "Father Age 28 — Business Plan Notebook",
        "summary": "Scanned pages from father's 2006 notebook outlining business idea with Amit.",
        "raw_text": "Father's 2006 notebook outlines a business plan with Amit. Margin notes mention grandfather's port job, discipline, and saving for family stories.",
        "structured_data": {
            "people": ["Father", "Amit", "Grandfather"],
            "places": ["Bangalore"],
            "events": ["Business planning"],
            "dates": ["2006"],
            "summary": "Early business planning before 2008 launch.",
        },
    },
    {
        "id": "fam_38",
        "title": "Hospital Recovery — Grandchildren's Drawings",
        "summary": "Grandchildren's drawings mailed to grandfather during 2024 hospital stay.",
        "raw_text": "During grandfather's 2024 hospital stay we mailed drawings from grandchildren. Nurses taped them near his bed beside father's recorder for story sessions.",
        "structured_data": {
            "people": ["Grandfather", "Father", "Me"],
            "places": ["Mumbai Hospital"],
            "events": ["Recovery", "Family care"],
            "dates": ["2024"],
            "summary": "Family love during grandfather's hospital recovery.",
        },
    },
    {
        "id": "fam_39",
        "title": "Duplicate Scan — Grandfather's Mumbai Childhood",
        "summary": "Duplicate upload of grandfather's Mumbai childhood story for merge testing.",
        "raw_text": "Grandfather told us he grew up in Dadar, Mumbai in the 1950s. His father worked at the docks and every evening the family gathered on the terrace.",
        "structured_data": {
            "people": ["Grandfather", "Great-grandfather"],
            "places": ["Dadar", "Mumbai"],
            "events": ["Childhood"],
            "dates": ["1954"],
            "summary": "Grandfather's childhood in Mumbai — duplicate scan.",
        },
    },
    {
        "id": "fam_40",
        "title": "Priya Joins Archive as Contributor",
        "summary": "Cousin Priya uploaded her Delhi photos after accepting family invite.",
        "raw_text": "Priya accepted our family invite and uploaded Delhi reunion photos. Father thanked her in the group chat and asked her to tag grandfather in every caption.",
        "structured_data": {
            "people": ["Priya", "Father", "Grandfather"],
            "places": ["Delhi", "Bangalore"],
            "events": ["Contributor upload", "Invite"],
            "dates": ["2024"],
            "summary": "Contributor added memories from Delhi branch.",
        },
    },
]
